### ISSUE TITLE
About mixture regression model and EM algorithm

### ISSUE THREAD

**Issue by schwarzichet** [Henrygwb/Explaining-DL#2]
The code here doesn't seem to include the mixture regression model part and EM algorithm part which are described in your LEMNA paper. Can you open source code for these part?

**Comment by Henrygwb** [comment]
Thanks for your question. The GMM-MEM and GMM are all mixture models, you can try that part first. Will release the mixture version of the fused lasso in the future. The current version is already  able to beat the baseline on the binary application.

**Comment by schwarzichet** [comment]
Actually I want to reproduce the results of RMSE in the LEMNA paper，while the code here seems to include fidelity tests only. And I tried fused lasso without mixture regression, but RMSE results show a kind of instability

**Comment by Henrygwb** [comment]
Could you provide me more details about your question via email? Thanks.
